---
title: "2020_028_Bombi - Progress Report"
author: "New Graph Environment"
date: 
output: 
  html_document:
    number_sections: true
    self_contained: yes
    css: corp-styles.css
    highlight: pygments
---



```{r setup, include = TRUE, echo =FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE,
                      fig.align="center", fig.width = 5.118, fig.height = 3.409,
                      fig.path = ('fig/'))
# knitr::opts_chunk$set(echo = TRUE)
source('R/packages.R')
source("R/functions.R")
```

```{r}
##import the data
fish_data_submission <- import_fish_data() 
```

```{r database-connect, eval = F}
source('R/private_info.R')
conn <- dbConnect(
  RPostgres::Postgres(),
  dbname = dbname,,
  host = host,
  port = port,
  user = user,
  password = password
)
```

```{r eval = F}
##find the closest modelled crossing 
##get the site locational data
site_location_data <-  fish_data_submission %>% 
  purrr::pluck("step_1_ref_and_loc_info") %>% 
  dplyr::filter(!is.na(site_number))%>% 
  mutate(survey_date = janitor::excel_numeric_to_date(as.numeric(survey_date)))

##make a spatial object
df <- site_location_data %>% 
  st_as_sf(crs = 26911, coords = c('utm_easting', 'utm_northing')) %>% 
  st_transform(crs = 3005)  %>% 
  mutate(hydro_map_id = case_when(reference_number == 1 ~ 13,
                                  T ~ 12))


# add a unique id - we could just use the reference number
df$misc_point_id <- seq.int(nrow(df))

# load to database
st_write(obj = df, dsn = conn, Id(schema= "public", table = "misc_points"))

# sf doesn't automagically create a spatial index or a primary key
res <- dbSendQuery(conn, "CREATE INDEX ON public.misc_points USING GIST (geometry)")
dbClearResult(res)
res <- dbSendQuery(conn, "ALTER TABLE public.misc_points ADD PRIMARY KEY (misc_point_id)")
dbClearResult(res)

df_info <- dbGetQuery(conn, "SELECT
  a.misc_point_id,
  b.*,
  ST_Distance(ST_Transform(a.geometry,3005), b.geom) AS distance
FROM
  public.misc_points AS a
CROSS JOIN LATERAL
  (SELECT *
   FROM fish_passage.modelled_crossings_closed_bottom
   ORDER BY
     a.geometry <-> geom
   LIMIT 1) AS b")

df_joined <- left_join(
  df,
  df_info,
  by = "misc_point_id"
) %>% 
  mutate(downstream_route_measure = as.integer(downstream_route_measure))

df_joined$blue_line_key
df_joined$downstream_route_measure
test <- fwa_watershed_at_measure(356555034, 400)


```

```{r eval=F}
##api not working right now....
wsheds_spat <-  get_watershed(fish_habitat_info = df_joined)
```

```{r database-connect2}
conn <- dbConnect(
  RPostgres::Postgres(),
  dbname = 'postgis',
  host = 'localhost',
  port = 5432,
  user = 'postgres',
  password = 'postgres'
)
```


```{r}
##grab the streams and roads
##mcphee is named_watershed_id 5814

query <- paste(
  'SELECT fh.* ',
  'FROM fish_passage.modelled_habitat_potential fh',
  'INNER JOIN',
  'whse_basemapping.fwa_named_watersheds_poly wg',
  'ON ST_Intersects(fh.geom,wg.geom)',
  'WHERE named_watershed_id IN',
  '(5814)'
)

streams <- st_read(conn, query = query) %>% 
  st_transform(crs = 4326)

query <- paste(
  'SELECT r.* ',
  'FROM  whse_basemapping.dra_dgtl_road_atlas_mpar_sp r',
  'INNER JOIN',
  'whse_basemapping.fwa_named_watersheds_poly wg',
  'ON ST_Intersects(r.geom,wg.geom)',
  'WHERE named_watershed_id IN',
  '(5814)'
)

rds <- st_read(conn, query = query) %>% 
  st_transform(crs = 4326)

```

```{r eval=F}
ggplot2::ggplot() +
    ggplot2::geom_sf(data = streams, lwd = 0.15) +
    ggplot2::geom_sf(data = test, lwd = 0.15, fill = 'steelblue', alpha = 0.5) 
  # ggplot2::geom_sf(data = yakoun, lwd = 0.15) 
```

```{r}
##find the closest modelled crossing 
##get the site locational data
site_location_data <-  fish_data_submission %>% 
  purrr::pluck("step_1_ref_and_loc_info") %>% 
  dplyr::filter(!is.na(site_number))%>% 
  mutate(survey_date = janitor::excel_numeric_to_date(as.numeric(survey_date)))

##make a spatial object
df <- site_location_data %>% 
  st_as_sf(crs = 26911, coords = c('utm_easting', 'utm_northing')) %>% 
  st_transform(crs = 3005)  %>% 
  mutate(hydro_map_id = case_when(reference_number == 1 ~ 13,
                                  T ~ 12))


# add a unique id - we could just use the reference number
df$misc_point_id <- seq.int(nrow(df))

# load to database
st_write(obj = df, dsn = conn, Id(schema= "public", table = "misc_points"))

# sf doesn't automagically create a spatial index or a primary key
res <- dbSendQuery(conn, "CREATE INDEX ON public.misc_points USING GIST (geometry)")
dbClearResult(res)
res <- dbSendQuery(conn, "ALTER TABLE public.misc_points ADD PRIMARY KEY (misc_point_id)")
dbClearResult(res)

##list column names in a table
# dbGetQuery(conn,
#            "SELECT column_name,data_type
#            FROM information_schema.columns
#            WHERE table_name='pscis_model_combined'")

##find the info for the closest crossings
##don't forget that the site is not necesary at the crossing location.  These ones match!!
df_info <- dbGetQuery(conn, "SELECT
  a.misc_point_id,
  b.*,
  ST_Distance(ST_Transform(a.geometry,3005), b.geom) AS distance
FROM
  public.misc_points AS a
CROSS JOIN LATERAL
  (SELECT *
   FROM fish_passage.pscis_model_combined
   ORDER BY
     a.geometry <-> geom
   LIMIT 1) AS b")



df_joined <- left_join(
  df,
  df_info,
  by = "misc_point_id"
)


```

```{r}
##extract the streams for the map


```


```{r get-watershed-codes}
#here is how we get the watershed codes - thanks Simon!!!! -- we should move this out of the functions file to a datbase of some sort I think - changed from crossing_id if we want to use model layer
wsheds <- dbGetQuery(conn, "SELECT DISTINCT ON (model_crossing_id) 
    a.model_crossing_id,
    a.linear_feature_id,
    b.watershed_code_50k,
    substring(b.watershed_code_50k from 1 for 3)
      ||'-'||substring(b.watershed_code_50k from 4 for 6)
      ||'-'||substring(b.watershed_code_50k from 10 for 6)
      ||'-'||substring(b.watershed_code_50k from 16 for 6)
      ||'-'||substring(b.watershed_code_50k from 24 for 6)
      ||'-'||substring(b.watershed_code_50k from 30 for 6)
      ||'-'||substring(b.watershed_code_50k from 36 for 6) as watershed_code_50k_parsed,
    b.blue_line_key_20k,
    b.watershed_key_20k,
    b.blue_line_key_50k,
    b.watershed_key_50k,
    b.match_type
FROM fish_passage.pscis_model_combined a
LEFT OUTER JOIN whse_basemapping.fwa_streams_20k_50k b
ON a.linear_feature_id = b.linear_feature_id_20k
WHERE a.watershed_group_code IN ('KOTL')
ORDER BY a.model_crossing_id, b.match_type;")

##add the watershed code back in
df_joined <- left_join(
  df_joined,
  select(wsheds, model_crossing_id, watershed_code_50k_parsed),
  by = "model_crossing_id"
)

```




```{r database-disconnect}
dbDisconnect(conn = conn)
```

```{r summarise-habitat, eval=T}
##now get the phase 2 sites only to add the habitat info
##bring in the data, make a html table of each row↑
habitat_data <- fish_data_submission %>% 
  pluck('step_4_stream_site_data')



habitat_data_summary <- habitat_data %>% 
  select(reference_number, gazetted_names, local_name, avg_channel_width_m, 
         avg_wetted_width_m,
         average_gradient_percent, comments) %>% 
  mutate(average_gradient_percent = average_gradient_percent * 100) %>% 
  mutate(across(where(is.numeric), round, 1)) %>% 
  # tidyr::separate(local_name, into = c('site_id', 'location'), remove = F) %>% 
  # dplyr::mutate(site_id = as.numeric(site_id)) %>% 
  dplyr::select(-local_name)


##join back to the rest of the info
df_joined <- left_join(
  df_joined,
  habitat_data_summary,
  by = 'reference_number'
) 

```

```{r georeference-photos}
files <- paste0('data/photos/',list.files('data/photos'))

photo_meta <- exifr::read_exif(path = files) %>% 
  purrr::set_names(., nm = tolower(names(.))) %>% 
  mutate(url  = paste0('https://github.com/NewGraphEnvironment/2020_028_bombi/raw/master/', 
                       sourcefile),
         base = tools::file_path_sans_ext(filename))
```

```{r leaflet-map}
# nhd_wms_url <- "https://basemap.nationalmap.gov/arcgis/services/USGSTopo/MapServer/WmsServer"
tracks <-  sf::read_sf("./data/field_cleaned.gpx", layer = "tracks") 


photo_meta <- read_csv("data/photo_meta.csv") %>% 
  mutate(base = tools::file_path_sans_ext(filename))

##transfor to wsg84
df_sf <- df_joined 

df_sf <- df_sf %>% 
  st_transform(crs = 4326)

##make colors for the priorities
# pal <- 
#    colorFactor(palette = c("red", "yellow", "green"), 
#                levels = c("Barrier", "Potential", "Passable"))


map <- leaflet(height=500, width=780) %>%
  # leaflet() %>% 
  addTiles() %>%
  leafem::addMouseCoordinates(proj4 = 26911) %>% ##can't seem to get it to render utms yet
  # addWMSTiles(nhd_wms_url, layers = "0") %>% 
  # addProviderTiles(providers$"Esri.DeLorme") %>% 
  addProviderTiles("Esri.WorldImagery", group = "ESRI Aerial") %>%
  addProviderTiles("Esri.WorldTopoMap", group = "Topo") %>%
  
  addPolylines(data=streams,  opacity=1, color = '#6498d2',
               fillOpacity = 0.75, weight=2) %>%
  addPolylines(data=rds,  opacity=1, color = '#ff7f00',
               fillOpacity = 0.75, weight=2) %>%
  addPolylines(data=tracks,  opacity=0.75, color = '#e216c4',
               fillOpacity = 0.75, weight=5) %>%
  # addLegend(
  #   position = "topright",
  #   colors = c("red", "yellow", "green"),
  #   labels = c("Barrier", "Potential Barrier", "Passable"), opacity = 1,
  #   title = "Bombi",
  # ) %>%
  addAwesomeMarkers(lng = photo_meta$gpslongitude,lat = photo_meta$gpslatitude,
                    popup = leafpop::popupImage(photo_meta$url, src = "remote"),
                    clusterOptions = markerClusterOptions(),
                    labelOptions = offset(c(0,0)),
                    label = paste0(photo_meta$filename)) %>%
    addCircleMarkers(
    data=df_sf,
    label = paste0('Site ', df_sf$reference_number),
    popup = leafpop::popupTable(x = select((df_sf %>% st_set_geometry(NULL)), 
                                           hydro_map_id, avg_channel_width_m,
                                           avg_wetted_width_m, average_gradient_percent,
                                           comments),
                                feature.id = F,
                                row.numbers = F), 
    radius = 9,
    fillColor = "red",
    color= "#ffffff",
    stroke = TRUE, 
    fillOpacity = 1.0,
    weight = 2,
    opacity = 1.0
  ) %>% 
  addScaleBar(position = 'bottomleft', options = scaleBarOptions(imperial = FALSE)) %>% 
  addLayersControl(
    baseGroups = c(
      "ESRI Aerial",
      "Esri.DeLorme"
      ),
    # overlayGroups = c(my_tracks$`125000_ds_track`),
    options = layersControlOptions(collapsed = F)) %>%
  addFullscreenControl() %>% 
  
  addMiniMap(tiles = providers$"Esri.NatGeoWorldMap",
             zoomLevelOffset = -4)    # setView(lng = -105.644, lat = 51.618, zoom = 3) ##this becomes the latest and greatest pscis crossing utm
map

```

```{r include= FALSE, echo=FALSE, comment=NA, message=FALSE, warning=FALSE, eval=F}

rmarkdown::render(input = paste0('report-progress.Rmd'),  
                    output_file = 'docs/index.html') 
```
